"""Optional self-hosted provider (vLLM, OpenAI-compatible) — SRS §8.4 Tier 3.

Reached through the same AIProvider interface so switching is config-only (D9).
Same metadata-only contract applies. Uses httpx against an OpenAI-compatible
/chat/completions endpoint to avoid an extra SDK dependency.
"""

from __future__ import annotations

import json

import httpx

from app.ai.anthropic_provider import _extract_json, _fields_payload
from app.ai.base import (
    AIMappingResult,
    AIProvider,
    AISpecResult,
    ExcelColumnMeta,
    FieldMetadata,
)
from app.ai.prompts.system_prompts import (
    ADJUST_SYSTEM,
    DERIVE_FIELD_SYSTEM,
    EXCEL_MAPPING_SYSTEM,
    NL_SYSTEM,
)
from app.core.config import settings


def _error_detail(resp: "httpx.Response") -> str:
    """Best human-readable reason from an error response — OpenAI-style {error:{message}},
    a bare {message}, else the raw body (truncated)."""
    try:
        body = resp.json()
    except Exception:  # noqa: BLE001 - non-JSON error body
        return (resp.text or "")[:300]
    if isinstance(body, dict):
        err = body.get("error")
        if isinstance(err, dict) and err.get("message"):
            return str(err["message"])[:300]
        if isinstance(err, str) and err:
            return err[:300]
        if body.get("message"):
            return str(body["message"])[:300]
    return (resp.text or "")[:300]


class SelfHostedProvider(AIProvider):
    """OpenAI-compatible chat/completions provider (vLLM, internal AI proxy, …).

    Supports an optional Bearer token (sent as `Authorization`) for gateways like
    ai-proxy.minchy.ai that require auth. Still metadata-only — same boundary."""

    def __init__(
        self, *, base_url: str | None = None, model: str | None = None, api_key: str | None = None
    ) -> None:
        self._base = (base_url or settings.selfhosted_base_url).rstrip("/")
        self._model = model or settings.selfhosted_model
        self._api_key = api_key
        # Optional output cap. Send max_tokens ONLY when explicitly set to a positive
        # value — otherwise omit it (the model stops naturally at finish_reason=stop).
        # Sending a computed budget risked (a) a non-positive value -> LiteLLM 400, and
        # (b) truncating a JSON response mid-way (finish_reason=length) -> invalid JSON.
        self._max_tokens = settings.selfhosted_max_tokens

    def _complete(self, system: str, user: str) -> str:
        headers = {"Content-Type": "application/json"}
        if self._api_key:
            headers["Authorization"] = f"Bearer {self._api_key}"
        url = f"{self._base}/chat/completions"
        payload: dict = {
            "model": self._model,
            "user": "MintHRM-Report-Builder",  # lets the proxy attribute the call
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
        }
        if (self._max_tokens or 0) > 0:
            payload["max_tokens"] = self._max_tokens
        resp = httpx.post(url, headers=headers, json=payload, timeout=90)
        # Surface the endpoint's OWN error message — a bare "400 Bad Request" hides the
        # real cause (unknown model, unsupported field, context overflow, wrong path…).
        if resp.status_code >= 400:
            # Detail FIRST so the real reason survives any UI truncation.
            raise ValueError(
                f"{_error_detail(resp)} — HTTP {resp.status_code} from the AI endpoint"
                f"{self._path_hint(resp.status_code, url)}"
            )
        data = resp.json()
        content = ((data.get("choices") or [{}])[0].get("message") or {}).get("content")
        if not content:
            raise ValueError(
                "The AI returned an empty response — the request may be too large for this "
                "model. Try a sheet with fewer columns, or use a larger-context model."
            )
        return content

    @staticmethod
    def _path_hint(status: int, url: str) -> str:
        """A nudge when the URL shape is the likely cause (missing /v1 on a 404)."""
        if status == 404 and "/v1/" not in url:
            return " (the endpoint wasn’t found — try adding /v1 to the Base URL)"
        return ""

    def natural_language(self, request: str, fields: list[FieldMetadata]) -> AISpecResult:
        user = f"AVAILABLE FIELDS:\n{_fields_payload(fields)}\n\nREPORT REQUEST:\n{request}"
        return AISpecResult(
            data_spec=_extract_json(self._complete(NL_SYSTEM, user)),
            rationale="Generated by self-hosted model.",
        )

    def adjustment_chat(
        self, instruction: str, current_spec: dict, fields: list[FieldMetadata]
    ) -> AISpecResult:
        user = (
            f"AVAILABLE FIELDS:\n{_fields_payload(fields)}\n\n"
            f"CURRENT SPEC:\n{json.dumps(current_spec, ensure_ascii=False)}\n\n"
            f"INSTRUCTION:\n{instruction}"
        )
        return AISpecResult(
            data_spec=_extract_json(self._complete(ADJUST_SYSTEM, user)),
            rationale="Updated by self-hosted model.",
        )

    def derive_field(self, description: str, fields: list[FieldMetadata]) -> dict:
        user = f"AVAILABLE FIELDS:\n{_fields_payload(fields)}\n\nDESCRIBE THE COLUMN:\n{description}"
        return _extract_json(self._complete(DERIVE_FIELD_SYSTEM, user))

    def excel_mapping(
        self, columns: list[ExcelColumnMeta], fields: list[FieldMetadata]
    ) -> AIMappingResult:
        cols = json.dumps(
            [{"header": c.header, "inferred_type": c.inferred_type} for c in columns]
        )
        user = f"AVAILABLE FIELDS:\n{_fields_payload(fields)}\n\nUPLOADED HEADERS (rows stripped):\n{cols}"
        result = _extract_json(self._complete(EXCEL_MAPPING_SYSTEM, user))
        return AIMappingResult(
            mappings=result.get("mappings", []), rationale=result.get("rationale", "")
        )
