<#
.SYNOPSIS
  Re-sync DataHub + semantic_catalog.yaml after Datamart warehouse or agent changes.

.DESCRIPTION
  Run from repo root whenever you change:
  - Warehouse schema (new tables/columns) or DATAMART_* in backend/.env
  - datahub_ingestion.yml schema_pattern
  - Datamart agent prompts, semantic_catalog.yaml, or join_hints

  Steps:
    1. DataHub ingest (recipe built from backend/.env - no duplicate passwords in YAML)
    2. semantic_catalog_tool.py refresh (dry-run, then --write)
    3. validate

.PARAMETER SkipDatahub
  Skip DataHub ingest (catalog refresh only).

.PARAMETER SkipCatalog
  Skip semantic catalog refresh/validate.

.PARAMETER SkipValidate
  Skip final validate step.

.PARAMETER TenantEtl
  Ingest tenant ETL warehouse (hr_semantic, hr, hr_snap) using tools/generate_tenant_datahub_ingest.py.
  Requires DATAMART_PROFILE=tenant_etl and DATAMART_DB_* pointing at hrm_wh_*.

.PARAMETER TenantId
  Tenant id for -TenantEtl (default: demo_tenant or DATAMART_DEFAULT_TENANT_ID from .env).

.EXAMPLE
  .\scripts\refresh_datamart_metadata.ps1

.EXAMPLE
  .\scripts\after_datamart_change.ps1
#>
param(
    [switch] $SkipDatahub,
    [switch] $SkipCatalog,
    [switch] $SkipValidate,
    [switch] $TenantEtl,
    [string] $TenantId = ""
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
$BackendEnv = Join-Path $Root "backend\.env"
$BackendDir = Join-Path $Root "backend"

function Import-DotEnvFile {
    param([string] $Path)
    if (-not (Test-Path $Path)) {
        Write-Warning "No backend/.env at $Path - using process environment only."
        return
    }
    Get-Content $Path | ForEach-Object {
        $line = $_.Trim()
        if (-not $line -or $line.StartsWith("#")) { return }
        $eq = $line.IndexOf("=")
        if ($eq -lt 1) { return }
        $key = $line.Substring(0, $eq).Trim()
        $val = $line.Substring($eq + 1).Trim()
        if (
            ($val.StartsWith('"') -and $val.EndsWith('"')) -or
            ($val.StartsWith("'") -and $val.EndsWith("'"))
        ) {
            $val = $val.Substring(1, $val.Length - 2)
        }
        [Environment]::SetEnvironmentVariable($key, $val, "Process")
    }
}

function Get-RequiredEnv {
    param([string] $Name, [string] $Default = "")
    $v = [Environment]::GetEnvironmentVariable($Name, "Process")
    if ($null -eq $v -or [string]::IsNullOrWhiteSpace($v)) {
        if ($Default) { return $Default }
        throw "Missing $Name - set it in backend/.env"
    }
    return $v.Trim()
}

function Write-DatahubRecipeFromEnv {
    param([string] $OutPath)
    $dbHost = Get-RequiredEnv "DATAMART_DB_HOST"
    $port = Get-RequiredEnv "DATAMART_DB_PORT" "10000"
    $db = Get-RequiredEnv "DATAMART_DB_NAME" "warehouse"
    $user = Get-RequiredEnv "DATAMART_DB_USER"
    $pass = Get-RequiredEnv "DATAMART_DB_PASSWORD"
    $schema = Get-RequiredEnv "DATAMART_SCHEMA" "public_mint_audit"
    $gms = Get-RequiredEnv "DATAHUB_GMS_URL" "http://localhost:8080"
    $token = [Environment]::GetEnvironmentVariable("DATAHUB_GMS_TOKEN", "Process")
    $tokenLine = ""
    if (-not [string]::IsNullOrWhiteSpace($token)) {
        $escaped = $token.Trim() -replace '"', '\"'
        $tokenLine = "    token: `"$escaped`"`n"
    }

    $lines = @(
        "# Generated by scripts/refresh_datamart_metadata.ps1 - do not commit"
        "source:"
        "  type: postgres"
        "  config:"
        "    host_port: `"${dbHost}:${port}`""
        "    database: `"$db`""
        "    username: `"$user`""
        "    password: `"$pass`""
        "    schema_pattern:"
        "      allow:"
        "        - `"$schema`""
        ""
        "sink:"
        "  type: datahub-rest"
        "  config:"
        "    server: `"$gms`""
    )
    if ($tokenLine) {
        $lines += $tokenLine.TrimEnd()
    }
    Set-Content -Path $OutPath -Value ($lines -join "`n") -Encoding UTF8
    Write-Host "  Recipe: $OutPath (schema=$schema, host=$($dbHost):$port)"
}

Import-DotEnvFile -Path $BackendEnv
Set-Location $Root

Write-Host ""
Write-Host "=== Datamart metadata refresh ===" -ForegroundColor Cyan
Write-Host "Run this after warehouse / catalog / agent changes (see DATAHUB_SETUP.md)."
Write-Host ""

if (-not $SkipDatahub) {
    $datahubCmd = Get-Command datahub -ErrorAction SilentlyContinue
    if (-not $datahubCmd) {
        Write-Warning "DataHub CLI not found. Install: pip install acryl-datahub acryl-datahub[postgres]"
        Write-Warning "Skipping ingest. Use -SkipDatahub to silence this when catalog-only."
    } else {
        Write-Host "==> DataHub ingest" -ForegroundColor Green
        $generated = Join-Path $Root "datahub_ingestion.generated.yml"
        if ($TenantEtl) {
            Set-Location $BackendDir
            $env:PYTHONPATH = "."
            $tid = $TenantId
            if ([string]::IsNullOrWhiteSpace($tid)) {
                $tid = [Environment]::GetEnvironmentVariable("DATAMART_DEFAULT_TENANT_ID", "Process")
                if ([string]::IsNullOrWhiteSpace($tid)) { $tid = "demo_tenant" }
            }
            Write-Host "  Tenant ETL recipe for: $tid" -ForegroundColor Yellow
            python tools/generate_tenant_datahub_ingest.py --tenant-id $tid --write $generated
            if ($LASTEXITCODE -ne 0) { throw "generate_tenant_datahub_ingest failed" }
            Set-Location $Root
        } else {
            Write-DatahubRecipeFromEnv -OutPath $generated
        }
        datahub ingest -c $generated
        if ($LASTEXITCODE -ne 0) {
            throw "datahub ingest failed (exit $LASTEXITCODE). Is DataHub running? See DATAHUB_SETUP.md"
        }
    }
} else {
    Write-Host "==> DataHub ingest (skipped)" -ForegroundColor DarkGray
}

if (-not $SkipCatalog) {
    Set-Location $BackendDir
    $env:PYTHONPATH = "."

    $catalogArgs = @()
    if ($TenantEtl) {
        $tid = $TenantId
        if ([string]::IsNullOrWhiteSpace($tid)) {
            $tid = [Environment]::GetEnvironmentVariable("DATAMART_DEFAULT_TENANT_ID", "Process")
            if ([string]::IsNullOrWhiteSpace($tid)) { $tid = "demo_tenant" }
        }
        $catalogArgs += "--tenant", $tid
        Write-Host "  Semantic catalog tenant: $tid" -ForegroundColor Yellow
    }

    Write-Host "==> Semantic catalog refresh (dry-run)" -ForegroundColor Green
    python tools/semantic_catalog_tool.py refresh @catalogArgs
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

    Write-Host "==> Semantic catalog refresh (write)" -ForegroundColor Green
    python tools/semantic_catalog_tool.py refresh --write @catalogArgs
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
} else {
    Write-Host "==> Semantic catalog (skipped)" -ForegroundColor DarkGray
}

if (-not $SkipValidate -and -not $SkipCatalog) {
    Write-Host "==> Validate catalog" -ForegroundColor Green
    Set-Location $BackendDir
    $env:PYTHONPATH = "."
    python tools/semantic_catalog_tool.py validate @catalogArgs
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
}

Write-Host ""
Write-Host "Done. Restart the backend if DATAMART_* or DATAHUB_GMS_URL changed." -ForegroundColor Cyan
Write-Host ""
