#!/usr/bin/env bash
# Re-ingest DataHub, then refresh + validate semantic_catalog.yaml.
# Run from repository root after Datamart warehouse / catalog / agent changes.
#
# Requires: datahub CLI, backend/.env with DATAMART_* and optional DATAHUB_GMS_URL
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BACKEND_ENV="$ROOT/backend/.env"
cd "$ROOT"

load_env() {
  if [[ ! -f "$BACKEND_ENV" ]]; then
    echo "warn: no backend/.env — using existing environment"
    return
  fi
  set -a
  # shellcheck disable=SC1090
  source <(grep -v '^\s*#' "$BACKEND_ENV" | grep -v '^\s*$' | sed 's/\r$//')
  set +a
}

write_recipe() {
  : "${DATAMART_DB_HOST:?Set DATAMART_DB_HOST in backend/.env}"
  : "${DATAMART_DB_USER:?Set DATAMART_DB_USER in backend/.env}"
  : "${DATAMART_DB_PASSWORD:?Set DATAMART_DB_PASSWORD in backend/.env}"
  local port="${DATAMART_DB_PORT:-10000}"
  local db="${DATAMART_DB_NAME:-warehouse}"
  local schema="${DATAMART_SCHEMA:-public_mint_audit}"
  local gms="${DATAHUB_GMS_URL:-http://localhost:8080}"
  local token="${DATAHUB_GMS_TOKEN:-}"
  local out="$ROOT/datahub_ingestion.generated.yml"
  {
    cat <<EOF
# Generated by scripts/refresh_datamart_metadata.sh — do not commit
source:
  type: postgres
  config:
    host_port: "${DATAMART_DB_HOST}:${port}"
    database: "${db}"
    username: "${DATAMART_DB_USER}"
    password: "${DATAMART_DB_PASSWORD}"
    schema_pattern:
      allow:
        - "${schema}"
sink:
  type: datahub-rest
  config:
    server: "${gms}"
EOF
    if [ -n "$token" ]; then
      printf '    token: "%s"\n' "$(printf '%s' "$token" | sed 's/"/\\"/g')"
    fi
  } >"$out"
  echo "  Recipe: $out (schema=$schema)"
}

echo ""
echo "=== Datamart metadata refresh ==="
echo ""

load_env

if command -v datahub >/dev/null 2>&1; then
  echo "==> DataHub ingest"
  write_recipe
  datahub ingest -c "$ROOT/datahub_ingestion.generated.yml"
else
  echo "warn: datahub CLI not found — skipping ingest (pip install acryl-datahub)"
fi

cd "$ROOT/backend"
export PYTHONPATH=.

echo "==> Semantic catalog refresh (dry-run)"
python tools/semantic_catalog_tool.py refresh

echo "==> Semantic catalog refresh (write)"
python tools/semantic_catalog_tool.py refresh --write

echo "==> Validate catalog"
python tools/semantic_catalog_tool.py validate

echo ""
echo "Done. Restart the backend if DATAMART_* or DATAHUB_GMS_URL changed."
echo ""
